package euler;

/**
 * 
 * Each new term in the Fibonacci sequence is generated by adding
 * the previous two terms. By starting with 1 and 2, the first 10
 * terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million, find the sum of the
 * even-valued terms.
 * 
 * Answer: 4613732
 * 
 * @author gambitgeoff
 *
 */
public class Problem0002 
{
	public static void main(String []args)
	{
		System.out.println("Sum: " + sumEvenFib(1, 2, 4000000, 0));
	}
	
	public static int sumEvenFib(int inPrevious, int inCurrent, int inLimit, int inSum)
	{
		if (inCurrent < inLimit)
		{
//			System.out.println("Current: " + inCurrent);
			int next = inPrevious + inCurrent;
			if (inCurrent%2==0)
				inSum+=inCurrent;
			return sumEvenFib(inCurrent, next, inLimit, inSum);
		}
		return inSum;
	}
}
